CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_IMG_MANAGER=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_STAT=y
CONFIG_MCUMGR_TRANSPORT_BT_CONN_PARAM_CONTROL=y
#CONFIG_MCUMGR_TRANSPORT_BT_DYNAMIC_SVC_REGISTRATION=y
CONFIG_MCUMGR_TRANSPORT_BT_PERM_RW_ENCRYPT=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR=y
CONFIG_STATS=y
CONFIG_STREAM_FLASH=y
CONFIG_ZCBOR=y

#CONFIG_BT_ATT_LOG_LEVEL_DBG=y
#CONFIG_BT_SMP_LOG_LEVEL_DBG=y
#CONFIG_MCUMGR_LOG_LEVEL_DBG=y
#CONFIG_MCUMGR_TRANSPORT_LOG_LEVEL_DBG=y
